SRC=case01 case02 case03 case04 case05 case06 case07 case08 case09 case10 \
case11 case12 case13 case14 case15 case16 case17 case18 case19 case20 \
case21 case22 case23 case24 case25 case26 case27 case28 case29 case30 \
case31 case32 case33 case34 case35 case36 case37 case38 case39 case40 \
case41 case42 case43 case44 case45 case46 case47 case48 case49 case50 \
case51 case52 case53 case54 case55 case56 case57_rbt case58 case59 case60 \
case61 case62 case63 case64 case65 case66 case67 case68 case69 case70 \
case71 case72 case73 case74 case75_gcc case76 case77 case78_nutos case79 case80 \
case81 case82 case83_linux_kernel case84 case85_preturn case86_preturn_cflow case87_trycatchthrow case88_get case89_set case90_aos \
case91_minfo case92 case93 case94_argtype case95_line case96_return_func_pointer

all: $(SRC)

$(SRC): force
	cd $@ ; make

clean:	force
	rm -rf */working

force:

