SRC=ex1 ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18 
#SRC2=ex1 ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18
all: $(SRC)

$(SRC): force
	cd $@ ; make

clean:

	cd ex1 ; make clean;\
	cd ../ex2 ; make clean;\
	cd ../ex3 ; make clean;\
	cd ../ex4 ; make clean;\
	cd ../ex5 ; make clean;\
	cd ../ex6 ; make clean;\
	cd ../ex7 ; make clean;\
	cd ../ex8 ; make clean;\
	cd ../ex9 ; make clean;\
	cd ../ex10 ; make clean;\
	cd ../ex11 ; make clean;\
	cd ../ex12 ; make clean;\
	cd ../ex13 ; make clean;\
	cd ../ex14 ; make clean;\
	cd ../ex15 ; make clean;\
	cd ../ex16 ; make clean;\
	cd ../ex17 ; make clean;\
	cd ../ex18 ; make clean



force:

